SELECT 	
	pc.FIRST_NAME + ' ' + pc.LAST_NAME as Person_Completing
	,OCCUR_DATE
	,DISCOVER_DATE
	,f.DNAME
	,ISNULL(oe.DESCRIPTION, '') Order_Entry
	,ISNULL(m.DESCRIPTION, '') Medication
	,ISNULL(s.DESCRIPTION, '') Shipping
	,ISNULL(d.DESCRIPTION, '') Delivery
	,ISNULL(b.DESCRIPTION, '') Billing
	,ISNULL(c.DESCRIPTION, '') Cooking
	,ISNULL(ou.DESCRIPTION, '') Other
	,o.CREATED_AT
FROM 
	RPT_OCCUR o
	LEFT JOIN RPT_USERS pc 
		ON o.PERSON_COMPLETING = pc.ID
	LEFT JOIN RPT_REASONS oe
		ON o.ORDER_INTAKE = oe.ID
	LEFT JOIN RPT_REASONS m
		ON o.MEDICATION = m.ID
	LEFT JOIN RPT_REASONS s
		ON o.SHIPPING = s.ID
	LEFT JOIN RPT_REASONS d
		ON o.DELIVERY = d.ID
	LEFT JOIN RPT_REASONS b
		ON o.BILLING = b.ID
	LEFT JOIN RPT_REASONS c
		ON o.COOKING = c.ID
	LEFT JOIN RPT_REASONS ou
		ON o.OTHER = ou.ID
	LEFT JOIN CIPS.dbo.FAC f
		on o.FACILITY_CODE = f.DCODE

		select CREATED_AT,* from RPT_OCCUR