
CREATE TABLE [dbo].[RPT_OCCUR](
	[ID] [INT] IDENTITY(1,1) NOT NULL,
	[USER_ID] INT NOT NULL,
	[DISCOVER_DATE] [DATETIME] NOT NULL,
	[OCCUR_DATE] [DATETIME] NOT NULL,
	[USERNAME] [VARCHAR](50) NOT NULL,
	[FACILITY_CODE] [NCHAR](6) NOT NULL,
	[PATIENT_NAME] [VARCHAR](50) NULL,
	[PERSON_REPORTING] [VARCHAR](50) NULL,
	[PHONE] [VARCHAR](20) NULL,
	[PERSON_COMPLETING] [VARCHAR](50) NOT NULL,
	[ORDER_INTAKE] INT NULL,
	[MEDICATION] INT NULL,
	[SHIPPING] INT NULL,
	[DELIVERY] INT NULL,
	[BILLING] INT NULL,
	[COOKING] INT NULL,
	[OTHER] INT NULL,
	[TECH_ID] INT NULL,
	[RPH_ID] INT NULL,
	[EXPLANATION] VARCHAR(3000) NOT NULL,
	[CREATED_AT] [DATETIME] NULL,
	[CREATED_BY] [NCHAR](6) NULL,
	[UPDATED_AT] [DATETIME] NULL,
	[UPDATED_BY] [NCHAR](6) NULL,
 CONSTRAINT [PK_RPT_OCCUR] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY])

--DROP TABLE [dbo].[RPT_OCCUR]

SELECT * FROM RPT_CATEGORIES






