USE [RXBackend]
GO

CREATE TABLE [dbo].[RPT_ROLES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPTION] [varchar](50) NOT NULL,
 CONSTRAINT [PK_RPT_ROLES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[DESCRIPTION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

INSERT INTO RPT_ROLES values('Administrator')
INSERT INTO RPT_ROLES values('User')
INSERT INTO RPT_ROLES values('PharmTech')
INSERT INTO RPT_ROLES values('ShipTech')
INSERT INTO RPT_ROLES values('Admin')
SELECT * FROM RPT_ROLES


DBCC CHECKIDENT('RPT_ROLES', RESEED, 1)

select * from RPT_ROLES order by id

SET IDENTITY_INSERT RPT_ROLES ON
UPDATE RPT_ROLES SET ID = 4 WHERE DESCRIPTION = 'Admin'
SET IDENTITY_INSERT RPT_ROLES OFF

truncate table  RPT_ROLES


ALTER TABLE RPT_ROLES
ADD UNIQUE (DESCRIPTION);


