INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('BILL','Wrong prices','1','SYS       ','Feb 10 2020  3:24PM',NULL,NULL,'1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('COOK','Label does not match drug','1','SYS       ','Feb 10 2020  3:28PM',NULL,NULL,'1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('DEL','Late delivery','1','SYS       ','Feb 10 2020  3:19PM',NULL,NULL,'1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('MED','Out of Meds','1','SYS       ','Feb 10 2020  2:43PM',NULL,NULL,'1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('ORDIN','Mar info incorrect','1','SYS       ','Feb 10 2020  2:15PM',NULL,NULL,'1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('SHIP','Wrong Address','1','SYS       ','Feb 10 2020  3:09PM',NULL,NULL,'1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('BILL','Wrong patient on bill','2','SYS       ','Feb 10 2020  3:24PM','SYS       ','Feb 13 2020  4:23PM','1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('COOK','Wrong Qty','2','SYS       ','Feb 10 2020  3:29PM',NULL,NULL,'1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('DEL','Wrong address','2','SYS       ','Feb 10 2020  3:19PM',NULL,NULL,'1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('MED','Too few meds','2','SYS       ','Feb 10 2020  2:45PM',NULL,NULL,'1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('ORDIN','Active Rx info sent/received','2','SYS       ','Feb 10 2020  2:17PM',NULL,NULL,'1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('SHIP','Wrong label on med box','2','SYS       ','Feb 10 2020  3:10PM',NULL,NULL,'1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('BILL','Other thing','4','SYS       ','Feb 10 2020  3:25PM','SYS       ','Feb 12 2020 12:03PM','1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('COOK','Wrong type of card used','3','SYS       ','Feb 10 2020  3:30PM',NULL,NULL,'1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('DEL','Crushed box','3','SYS       ','Feb 10 2020  3:20PM',NULL,NULL,'1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('MED','Expired Meds','3','SYS       ','Feb 10 2020  2:45PM',NULL,NULL,'1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('ORDIN','Orders not received/entered','3','SYS       ','Feb 10 2020  2:29PM',NULL,NULL,'1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('SHIP','Med label in wrong place','3','SYS       ','Feb 10 2020  3:11PM',NULL,NULL,'1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('COOK','Each dose not cooked on separte card','4','SYS       ','Feb 10 2020  3:31PM',NULL,NULL,'1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('DEL','Opened box','4','SYS       ','Feb 10 2020  3:21PM',NULL,NULL,'1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('MED','Dosing schedule wrong','4','SYS       ','Feb 10 2020  2:47PM',NULL,NULL,'1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('SHIP','Meds sent to wrong facility','4','SYS       ','Feb 10 2020  3:11PM',NULL,NULL,'1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('DEL','Wrong med','5','SYS       ','Feb 10 2020  3:22PM',NULL,NULL,'1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('MED','Wrong med','5','SYS       ','Feb 10 2020  2:49PM',NULL,NULL,'1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('SHIP','Delivery sheet omitted','5','SYS       ','Feb 10 2020  3:14PM',NULL,NULL,'1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('MED','Wrong med strength','6','SYS       ','Feb 10 2020  2:49PM',NULL,NULL,'1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('SHIP','Delivery sheet incorrect','6','SYS       ','Feb 10 2020  3:15PM',NULL,NULL,'1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('MED','Wrong script','7','SYS       ','Feb 10 2020  3:05PM',NULL,NULL,'1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('SHIP','MAR not sent','7','SYS       ','Feb 10 2020  3:16PM',NULL,NULL,'1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('MED','Wrong start date','8','SYS       ','Feb 10 2020  3:05PM',NULL,NULL,'1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('SHIP','Wrong MAR sent','8','SYS       ','Feb 10 2020  3:17PM',NULL,NULL,'1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('MED','Formulary not followed','9','SYS       ','Feb 10 2020  3:06PM',NULL,NULL,'1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('SHIP','Other','9','SYS       ','Feb 10 2020  3:18PM',NULL,NULL,'1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('OU','Test another','1','SYS       ','Feb 13 2020 11:48AM','HDA       ','Feb 20 2020  6:16PM','1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('OU','Test add another','2','SYS       ','Feb 13 2020 11:49AM',NULL,NULL,'1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('OU','Test add another','5','HDA       ','Feb 23 2020  9:41AM',NULL,NULL,'1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('OU','Test other','12','HDA       ','Feb 23 2020  9:41AM',NULL,NULL,'1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('MED','Test','12','HDA       ','Feb 23 2020  9:43AM',NULL,NULL,'1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('COOK','test','3','HDA       ','Feb 23 2020  9:44AM',NULL,NULL,'1')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('BILL','Test Bill','9','HDA       ','Feb 23 2020  9:45AM','HDA       ','Feb 23 2020  9:51AM','0')
INSERT INTO RPT_REASONS([CATEGORY_CODE],[DESCRIPTION],[SORT_ORDER],[CREATED_BY],[CREATED],[LAST_USER],[LAST_UPDATE],[ACTIVE])VALUES('BILL','Test','9','HDA       ','Feb 23 2020  9:51AM',NULL,NULL,'1'

 --###############################################################################

 INSERT INTO [dbo].[RPT_CATEGORIES] ([CODE],[DESCRIPTION],[DEPT_CODE])
 VALUES ('ORDIN','Order Intake' ,'ALL')
GO

INSERT INTO [dbo].[RPT_CATEGORIES] ([CODE],[DESCRIPTION],[DEPT_CODE])
 VALUES ('MED','Medication' ,'ALL')

 INSERT INTO [dbo].[RPT_CATEGORIES] ([CODE],[DESCRIPTION],[DEPT_CODE])
 VALUES ('SHIP','Shipping' ,'ALL')

 INSERT INTO [dbo].[RPT_CATEGORIES] ([CODE],[DESCRIPTION],[DEPT_CODE])
 VALUES ('DEL','Delivery' ,'ALL')

  INSERT INTO [dbo].[RPT_CATEGORIES] ([CODE],[DESCRIPTION],[DEPT_CODE])
 VALUES ('BILL','Billing' ,'ALL')

  INSERT INTO [dbo].[RPT_CATEGORIES] ([CODE],[DESCRIPTION],[DEPT_CODE])
 VALUES ('COOK','Cooking' ,'ALL')

--###############################################################################

INSERT INTO RPT_ROLES values('Administrator')
INSERT INTO RPT_ROLES values('User')
INSERT INTO RPT_ROLES values('PharmTech')
INSERT INTO RPT_ROLES values('ShipTech')
INSERT INTO RPT_ROLES values('Admin')

--###############################################################################

CREATE TABLE [dbo].[DEPARTMENTS](
	[CODE] [nchar](20) NOT NULL,
	[DESCRIPTION] [nchar](30) NOT NULL,
 CONSTRAINT [PK_DEPARTMENTS] PRIMARY KEY CLUSTERED 
(
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

INSERT INTO RPT_USERS([USERNAME],[FIRST_NAME],[LAST_NAME],[POSITION],[PASSWORD],[SALT],[CREATED_AT],[CREATED_BY],[UPDATED_AT],[UPDATED_BY],[ACTIVE],[INITIALS])VALUES('hanka','Hank','Allen','Dev','pbkdf2:sha256:150000$6oDFAILg$339eb041e155e6d91d45af6d424469cad212a18fdadfe601b4b69da45519fb72','NOTIMPLEMENTED','Feb 14 2020  1:48PM','hanka ','Feb 17 2020  8:21AM','SYS   ','1','HDA   ')

USE [RXBackend]
GO

INSERT INTO [dbo].[DEPARTMENTS]([CODE] ,[DESCRIPTION])
VALUES('RX','Pharmacy')

INSERT INTO [dbo].[DEPARTMENTS]([CODE] ,[DESCRIPTION])
VALUES('TECH','Pharmacy Tech')

INSERT INTO [dbo].[DEPARTMENTS]([CODE] ,[DESCRIPTION])
VALUES('SHIP','Shipping')

INSERT INTO [dbo].[DEPARTMENTS]([CODE] ,[DESCRIPTION])
VALUES('ACCT','Accounting')

INSERT INTO [dbo].[DEPARTMENTS]([CODE] ,[DESCRIPTION])
VALUES('ALL','All')

--###############################################################################
select * from RPT_USER_ROLE
select * from RPT_USERS

USE [RXBackend]
GO

INSERT INTO [dbo].[RPT_USER_ROLE]
           ([USER_ID]
           ,[ROLE_ID])
     VALUES
           (1
           1)
GO



[dbo].[sp_generate_insertscripts] 'RPT_CATEGORIES'
INSERT INTO RPT_USERS([USERNAME],[FIRST_NAME],[LAST_NAME],[POSITION],[PASSWORD],[SALT],[CREATED_AT],[CREATED_BY],[UPDATED_AT],[UPDATED_BY],[ACTIVE],[INITIALS])VALUES('hanka','Hank','Allen','Dev','pbkdf2:sha256:150000$6oDFAILg$339eb041e155e6d91d45af6d424469cad212a18fdadfe601b4b69da45519fb72','NOTIMPLEMENTED','Feb 14 2020  1:48PM','hanka ','Feb 17 2020  8:21AM','SYS   ','1','HDA   ')
