CREATE TABLE [dbo].[RPT_USERS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USERNAME] [varchar](50) NOT NULL,
	[FIRST_NAME] [varchar](20) NOT NULL,
	[LAST_NAME] [varchar](20) NOT NULL,
	[POSITION] [varchar](30) NOT NULL,
	[PASSWORD] [varchar](160) NOT NULL,
	[SALT] [varchar](50) NOT NULL,
	[CREATED_AT] [datetime] NULL,
	[CREATED_BY] [nchar](6) NULL,
	[UPDATED_AT] [datetime] NULL,
	[UPDATED_BY] [nchar](6) NULL,
	[ACTIVE] [bit] NOT NULL,
	[INITIALS] [nchar](6) NULL,
 CONSTRAINT [PK_RPT_USER] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[INTIALS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RPT_USERS] ADD  CONSTRAINT [DF_RPT_USERS_CREATED_AT]  DEFAULT (getdate()) FOR [CREATED_AT]
GO

ALTER TABLE [dbo].[RPT_USERS] ADD  CONSTRAINT [DF_RPT_USERS_ACTIVE]  DEFAULT ((1)) FOR [ACTIVE]
GO



select * from users where username like 'hank%'
select * from RPT_USERS where username like 'hank%'
select * from RPT_USER_ROLE
select * from RPT_ROLES

