CREATE TABLE [dbo].[RPT_REASONS](
	[CODE] [nvarchar](20) NOT NULL,
	[CATEGORY_CODE] [nvarchar](20) NOT NULL,
	[DESCRIPTION] [nvarchar](100) NOT NULL,
	[SORT_ORDER] [int] NULL,
	[CREATED_BY] [nchar](10) NOT NULL,
	[CREATED] [datetime] NOT NULL,
	[LAST_USER] [nchar](10) NULL,
	[LAST_UPDATE] [datetime] NULL,
	[ACTIVE] [bit] NOT NULL,
 CONSTRAINT [PK_RPT_REASONS] PRIMARY KEY CLUSTERED 
(
	[CODE] ASC,
	[CATEGORY_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RPT_REASONS] ADD  CONSTRAINT [DF_RPT_REASONS_SORT_ORDER]  DEFAULT ((1)) FOR [SORT_ORDER]
GO

ALTER TABLE [dbo].[RPT_REASONS] ADD  CONSTRAINT [DF_RPT_REASONS_CREATED]  DEFAULT (getdate()) FOR [CREATED]
GO

ALTER TABLE [dbo].[RPT_REASONS] ADD  CONSTRAINT [DF_RPT_REASONS_ACTIVE]  DEFAULT ((1)) FOR [ACTIVE]
GO





ALTER TABLE table_name
DROP CONSTRAINT constraint_name;



 --Update [dbo].[RPT_REASONS] set CATEGORY_CODE = 'ORDIN', CODE = REPLACE(CODE, 'BILL', '')
 --where code

 Update [dbo].[RPT_REASONS] set SORT_ORDER = CAST(REPLACE(CODE, '00', '') AS int)
  Update [dbo].[RPT_REASONS] set DESCRIPTION = 'Other' where CODE='003' and CATEGORY_CODE = 'BILL'

 SELECT REPLACE(CODE, 'BILL', ''), CAST(REPLACE(CODE, '00', '') AS int) from [dbo].[RPT_REASONS]

SELECT * from [dbo].[RPT_REASONS] order by CREATED desc

DELETE from [dbo].[RPT_REASONS] where DESCRIPTION like 'Test%'


INSERT INTO [dbo].[RPT_REASONS] 
([CODE],[CATEGORY_CODE],[DESCRIPTION],[CREATED_BY],[CREATED], SORT_ORDER)
 VALUES('001','ORDIN','Mar info incorrect','SYS',GETDATE(),1)

 INSERT INTO [dbo].[RPT_REASONS] 
([CODE],[CATEGORY_CODE],[DESCRIPTION],[CREATED_BY],[CREATED], SORT_ORDER)
 VALUES('002','ORDIN','Active Rx info sent/received','SYS',GETDATE(),2)

INSERT INTO [dbo].[RPT_REASONS] 
([CODE],[CATEGORY_CODE],[DESCRIPTION],[CREATED_BY],[CREATED],[SORT_ORDER])
 VALUES('003','ORDIN','Orders not received/entered','SYS',GETDATE(),3)


 INSERT INTO [dbo].[RPT_REASONS] 
([CODE],[CATEGORY_CODE],[DESCRIPTION],[CREATED_BY],[CREATED],[SORT_ORDER])
 VALUES('001','MED','Out of Meds','SYS',GETDATE(),1)

 INSERT INTO [dbo].[RPT_REASONS] 
([CODE],[CATEGORY_CODE],[DESCRIPTION],[CREATED_BY],[CREATED],[SORT_ORDER])
 VALUES('002','MED','Too few meds','SYS',GETDATE(),2)

INSERT INTO [dbo].[RPT_REASONS] 
([CODE],[CATEGORY_CODE],[DESCRIPTION],[CREATED_BY],[CREATED],[SORT_ORDER])
 VALUES('003','MED','Expired Meds','SYS',GETDATE(),3)

 INSERT INTO [dbo].[RPT_REASONS] 
([CODE],[CATEGORY_CODE],[DESCRIPTION],[CREATED_BY],[CREATED],[SORT_ORDER])
 VALUES('004','MED','Dosing schedule wrong','SYS',GETDATE(),4)

  INSERT INTO [dbo].[RPT_REASONS] 
([CODE],[CATEGORY_CODE],[DESCRIPTION],[CREATED_BY],[CREATED],[SORT_ORDER])
 VALUES('005','MED','Wrong med','SYS',GETDATE(),5)

 
  INSERT INTO [dbo].[RPT_REASONS] 
([CODE],[CATEGORY_CODE],[DESCRIPTION],[CREATED_BY],[CREATED],[SORT_ORDER])
 VALUES('006','MED','Wrong med strength','SYS',GETDATE(),6)

 INSERT INTO [dbo].[RPT_REASONS] 
([CODE],[CATEGORY_CODE],[DESCRIPTION],[CREATED_BY],[CREATED],[SORT_ORDER])
 VALUES('007','MED','Wrong script','SYS',GETDATE(),7)

  INSERT INTO [dbo].[RPT_REASONS] 
([CODE],[CATEGORY_CODE],[DESCRIPTION],[CREATED_BY],[CREATED],[SORT_ORDER])
 VALUES('008','MED','Wrong start date','SYS',GETDATE(),8)

INSERT INTO [dbo].[RPT_REASONS] 
([CODE],[CATEGORY_CODE],[DESCRIPTION],[CREATED_BY],[CREATED],[SORT_ORDER])
 VALUES('009','MED','Formulary not followed','SYS',GETDATE(),9)

 INSERT INTO [dbo].[RPT_REASONS] 
([CODE],[CATEGORY_CODE],[DESCRIPTION],[CREATED_BY],[CREATED],[SORT_ORDER])
 VALUES('010','MED','Other','SYS',GETDATE(),10)

 INSERT INTO [dbo].[RPT_REASONS] 
([CODE],[CATEGORY_CODE],[DESCRIPTION],[CREATED_BY],[CREATED],[SORT_ORDER])
 VALUES('001','SHIP','Wrong Address','SYS',GETDATE(),1)

 INSERT INTO [dbo].[RPT_REASONS] 
([CODE],[CATEGORY_CODE],[DESCRIPTION],[CREATED_BY],[CREATED],[SORT_ORDER])
 VALUES('002','SHIP','Wrong label on med box','SYS',GETDATE(),2)

 INSERT INTO [dbo].[RPT_REASONS] 
([CODE],[CATEGORY_CODE],[DESCRIPTION],[CREATED_BY],[CREATED],[SORT_ORDER])
 VALUES('003','SHIP','Med label in wrong place','SYS',GETDATE(),3)

  INSERT INTO [dbo].[RPT_REASONS] 
([CODE],[CATEGORY_CODE],[DESCRIPTION],[CREATED_BY],[CREATED],[SORT_ORDER])
 VALUES('004','SHIP','Meds sent to wrong facility','SYS',GETDATE(),4)

 
  INSERT INTO [dbo].[RPT_REASONS] 
([CODE],[CATEGORY_CODE],[DESCRIPTION],[CREATED_BY],[CREATED],[SORT_ORDER])
 VALUES('005','SHIP','Delivery sheet omitted','SYS',GETDATE(),5)


INSERT INTO [dbo].[RPT_REASONS] 
([CODE],[CATEGORY_CODE],[DESCRIPTION],[CREATED_BY],[CREATED],[SORT_ORDER])
 VALUES('006','SHIP','Delivery sheet incorrect','SYS',GETDATE(),6)

 INSERT INTO [dbo].[RPT_REASONS] 
([CODE],[CATEGORY_CODE],[DESCRIPTION],[CREATED_BY],[CREATED],[SORT_ORDER])
 VALUES('007','SHIP','MAR not sent','SYS',GETDATE(),7)

  INSERT INTO [dbo].[RPT_REASONS] 
([CODE],[CATEGORY_CODE],[DESCRIPTION],[CREATED_BY],[CREATED],[SORT_ORDER])
 VALUES('008','SHIP','Wrong MAR sent','SYS',GETDATE(),8)

   INSERT INTO [dbo].[RPT_REASONS] 
([CODE],[CATEGORY_CODE],[DESCRIPTION],[CREATED_BY],[CREATED],[SORT_ORDER])
 VALUES('009','SHIP','Other','SYS',GETDATE(),9)

INSERT INTO [dbo].[RPT_REASONS] 
([CODE],[CATEGORY_CODE],[DESCRIPTION],[CREATED_BY],[CREATED],[SORT_ORDER])
 VALUES('001','DEL','Late delivery','SYS',GETDATE(),1)

 INSERT INTO [dbo].[RPT_REASONS] 
([CODE],[CATEGORY_CODE],[DESCRIPTION],[CREATED_BY],[CREATED],[SORT_ORDER])
 VALUES('002','DEL','Wrong address','SYS',GETDATE(),2)

  INSERT INTO [dbo].[RPT_REASONS] 
([CODE],[CATEGORY_CODE],[DESCRIPTION],[CREATED_BY],[CREATED],[SORT_ORDER])
 VALUES('003','DEL','Crushed box','SYS',GETDATE(),3)

   INSERT INTO [dbo].[RPT_REASONS] 
([CODE],[CATEGORY_CODE],[DESCRIPTION],[CREATED_BY],[CREATED],[SORT_ORDER])
 VALUES('004','DEL','Opened box','SYS',GETDATE(),4)

    INSERT INTO [dbo].[RPT_REASONS] 
([CODE],[CATEGORY_CODE],[DESCRIPTION],[CREATED_BY],[CREATED],[SORT_ORDER])
 VALUES('005','DEL','Wrong med','SYS',GETDATE(),5)

 INSERT INTO [dbo].[RPT_REASONS] 
([CODE],[CATEGORY_CODE],[DESCRIPTION],[CREATED_BY],[CREATED],[SORT_ORDER])
 VALUES('006','DEL','Wrong med','SYS',GETDATE(),6)

 
INSERT INTO [dbo].[RPT_REASONS] 
([CODE],[CATEGORY_CODE],[DESCRIPTION],[CREATED_BY],[CREATED],[SORT_ORDER])
 VALUES('001','BILL','Wrong prices','SYS',GETDATE(),1)

 INSERT INTO [dbo].[RPT_REASONS] 
([CODE],[CATEGORY_CODE],[DESCRIPTION],[CREATED_BY],[CREATED],[SORT_ORDER])
 VALUES('002','BILL','Wrong patient on bill','SYS',GETDATE(),2)

  INSERT INTO [dbo].[RPT_REASONS] 
([CODE],[CATEGORY_CODE],[DESCRIPTION],[CREATED_BY],[CREATED],[SORT_ORDER])
 VALUES('003','BILL','Other','SYS',GETDATE(),3)

 INSERT INTO [dbo].[RPT_REASONS] 
([CODE],[CATEGORY_CODE],[DESCRIPTION],[CREATED_BY],[CREATED],[SORT_ORDER])
 VALUES('001','COOK','Label does not match drug','SYS',GETDATE(),1)

 INSERT INTO [dbo].[RPT_REASONS] 
([CODE],[CATEGORY_CODE],[DESCRIPTION],[CREATED_BY],[CREATED],[SORT_ORDER])
 VALUES('002','COOK','Wrong Qty','SYS',GETDATE(),2)

 INSERT INTO [dbo].[RPT_REASONS] 
([CODE],[CATEGORY_CODE],[DESCRIPTION],[CREATED_BY],[CREATED],[SORT_ORDER])
 VALUES('003','COOK','Wrong type of card used','SYS',GETDATE(),3)

  INSERT INTO [dbo].[RPT_REASONS] 
([CODE],[CATEGORY_CODE],[DESCRIPTION],[CREATED_BY],[CREATED],[SORT_ORDER])
 VALUES('004','COOK','Each dose not cooked on separte card','SYS',GETDATE(),4)








