USE [RXBackend]
GO

/****** Object:  Table [dbo].[RPT_CATEGORIES]    Script Date: 2/10/2020 12:53:02 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RPT_CATEGORIES](
	[CODE] [nchar](20) NOT NULL,
	[DESCRIPTION] [nchar](100) NOT NULL,
	[DEPT_CODE] [nchar](20) NOT NULL,
 CONSTRAINT [PK_RPT_CATEGORIES] PRIMARY KEY CLUSTERED 
(
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [RXBackend]
GO

INSERT INTO [dbo].[RPT_CATEGORIES] ([CODE],[DESCRIPTION],[DEPT_CODE])
 VALUES ('ORDIN','Order Intake' ,'ALL')
GO

INSERT INTO [dbo].[RPT_CATEGORIES] ([CODE],[DESCRIPTION],[DEPT_CODE])
 VALUES ('MED','Medication' ,'ALL')

 INSERT INTO [dbo].[RPT_CATEGORIES] ([CODE],[DESCRIPTION],[DEPT_CODE])
 VALUES ('SHIP','Shipping' ,'ALL')

 INSERT INTO [dbo].[RPT_CATEGORIES] ([CODE],[DESCRIPTION],[DEPT_CODE])
 VALUES ('DEL','Delivery' ,'ALL')

  INSERT INTO [dbo].[RPT_CATEGORIES] ([CODE],[DESCRIPTION],[DEPT_CODE])
 VALUES ('BILL','Billing' ,'ALL')

  INSERT INTO [dbo].[RPT_CATEGORIES] ([CODE],[DESCRIPTION],[DEPT_CODE])
 VALUES ('COOK','Cooking' ,'ALL')

 SELECT * from [dbo].[RPT_CATEGORIES]
  SELECT * from [dbo].[RPT_REASONS]




