SELECT
    CAST RPT_OCCUR.DISCOVER_DATE, 
	RPT_OCCUR.OCCUR_DATE, 	
	RPT_OCCUR.CREATED_AT,
	CASE WHEN TECH_REQ_VERIFY <> 0 AND TECH_VERIFY_DATE IS NULL 
		THEN  RPT_USERS_TECH.FIRST_NAME + ' ' + RPT_USERS_TECH.LAST_NAME
	ELSE '' END AS TECH_NAME,
	CASE WHEN RPH_REQ_VERIFY <> 0 AND RPH_VERIFY_DATE IS NULL 
		THEN  RPT_USERS_RPH.FIRST_NAME + ' ' + RPT_USERS_RPH.LAST_NAME
	ELSE '' END AS RPH_NAME,

	CASE WHEN TECH_REQ_VERIFY <> 0 AND TECH_VERIFY_DATE IS NULL 
		THEN  TECH_ID
	ELSE 0 END AS TECH_ID_SIGN,
	CASE WHEN RPH_REQ_VERIFY <> 0 AND RPH_VERIFY_DATE IS NULL 
		THEN  RPH_ID
	ELSE 0 END AS RPH_ID_SIGN,

	RPT_OCCUR.FACILITY_CODE, 
	RPT_OCCUR.PATIENT_NAME,  
	RPT_OCCUR.EXPLANATION,
    FAC.DNAME,
	RPT_OCCUR.PERSON_REPORTING,
    RPT_REASONS.DESCRIPTION REASON,
	RPT_USERS_TECH.FIRST_NAME, RPT_USERS_TECH.LAST_NAME,
    RPT_USERS_RPH.FIRST_NAME, RPT_USERS_RPH.LAST_NAME,
    RPT_CATEGORIES.DESCRIPTION DEPT,
	RPT_OCCUR.TECH_REQ_VERIFY,
	RPT_OCCUR.TECH_VERIFY_DATE,
	RPT_OCCUR.RPH_REQ_VERIFY,
	RPT_OCCUR.RPH_VERIFY_DATE,
	RPT_OCCUR.TECH_ID,
	RPT_OCCUR.RPH_ID,
	RPT_OCCUR.PERSON_COMPLETING
FROM
    RXBackend.dbo.RPT_OCCUR RPT_OCCUR 
	LEFT OUTER JOIN RXBackend.dbo.RPT_REASONS RPT_REASONS ON
        RPT_OCCUR.REASON_CODE = RPT_REASONS.ID
     LEFT OUTER JOIN RXBackend.dbo.RPT_USERS RPT_USERS_RPH ON
        RPT_OCCUR.RPH_ID = RPT_USERS_RPH.ID
     LEFT OUTER JOIN RXBackend.dbo.RPT_USERS RPT_USERS_TECH ON
        RPT_OCCUR.TECH_ID = RPT_USERS_TECH.ID
     LEFT OUTER JOIN RXBackend.dbo.FAC FAC ON
        RPT_OCCUR.FACILITY_CODE = FAC.DCODE
     LEFT OUTER JOIN RXBackend.dbo.RPT_CATEGORIES RPT_CATEGORIES ON
        RPT_REASONS.CATEGORY_CODE = RPT_CATEGORIES.CODE
WHERE (RPH_REQ_VERIFY <> 0 AND RPH_VERIFY_DATE IS NULL) OR (TECH_REQ_VERIFY <> 0 AND TECH_VERIFY_DATE IS NULL)

--SELECT * FROM RPT_OCCUR
--WHERE (RPH_REQ_VERIFY <> 0 AND RPH_VERIFY_DATE IS NULL) OR (TECH_REQ_VERIFY <> 0 AND TECH_VERIFY_DATE IS NULL)

--UPDATE RPT_OCCUR SET TECH_VERIFY_DATE = null
--WHERE ID = 203


